# Generated by Django 4.0.5 on 2022-06-16 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10)),
                ('slug', models.SlugField(max_length=250, unique_for_date='published')),
                ('country', models.CharField(blank=True, max_length=255)),
                ('assignment', models.CharField(max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('client_name', models.CharField(max_length=255, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('completion_Date', models.DateTimeField(auto_now=True)),
                ('amount_Of_project', models.CharField(max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('worker', models.IntegerField()),
                ('officer', models.CharField(blank=True, max_length=255)),
                ('description_of_project', models.TextField()),
                ('service_description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='post.category')),
            ],
        ),
    ]
