# Generated by Django 4.0.5 on 2022-06-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_amount_of_project_post_amount_of_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('desc', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='event')),
            ],
        ),
    ]
